# Generated by Django 2.0.1 on 2018-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(verbose_name='源码')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('public', models.BooleanField(default=False, verbose_name='公开代码')),
                ('language', models.CharField(default='C++', max_length=254, verbose_name='语言')),
                ('remote_run_id', models.CharField(max_length=254, null=True, verbose_name='原OJ运行id')),
                ('judge_result', models.CharField(max_length=254, null=True, verbose_name='裁判结果')),
                ('execute_time', models.CharField(max_length=254, null=True, verbose_name='程序运行时间')),
                ('execute_memory', models.CharField(max_length=254, null=True, verbose_name='程序运行内存')),
                ('compile_info', models.TextField(null=True, verbose_name='编译信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('spider_status', models.IntegerField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=False, to='contest.Contest', verbose_name='比赛')),
                ('problem', models.ForeignKey(null=True, on_delete=False, to='problem.Problem', verbose_name='题目')),
            ],
            options={
                'verbose_name': '提交记录',
                'verbose_name_plural': '提交记录',
            },
        ),
    ]
