# Generated by Django 2.0.1 on 2018-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='比赛名称')),
                ('description', models.TextField(verbose_name='比赛简介')),
                ('join_password', models.CharField(max_length=50, null=True, verbose_name='比赛口令')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_public', models.BooleanField(verbose_name='比赛公开')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
            },
        ),
    ]
