# Generated by Django 2.0.1 on 2018-04-18 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='manager',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='组织者'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='problem.Problem', verbose_name='比赛题目'),
        ),
    ]
