# Generated by Django 2.0.1 on 2018-04-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vjweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ojlanguage',
            unique_together={('oj', 'language_name', 'language_string')},
        ),
    ]
