# Generated by Django 2.0.1 on 2018-04-18 06:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_oj', models.CharField(max_length=254, null=True, verbose_name='原OJ')),
                ('remote_id', models.CharField(max_length=254, null=True, verbose_name='原OJ题目id')),
                ('remote_url', models.CharField(max_length=254, null=True, verbose_name='愿题目地址')),
                ('request_status', models.IntegerField(default=0, verbose_name='请求状态')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('title', models.CharField(max_length=254, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题面')),
                ('input_description', models.TextField(verbose_name='输入描述')),
                ('output_description', models.TextField(verbose_name='输出描述')),
                ('in_sample', models.TextField(verbose_name='输入样例')),
                ('out_sample', models.TextField(verbose_name='输出样咧')),
                ('hint', models.TextField(null=True, verbose_name='提示')),
                ('time_limit', models.CharField(max_length=254, verbose_name='时间限制')),
                ('memory_limit', models.CharField(max_length=254, verbose_name='内存限制')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('accepted', models.PositiveIntegerField(default=0, verbose_name='通过数')),
                ('submit', models.PositiveIntegerField(default=0, verbose_name='提交数')),
                ('source', models.CharField(default='defaultnull', max_length=254, null=True, verbose_name='来源')),
                ('special_judge', models.BooleanField(default=False, verbose_name='SPJ')),
                ('sample', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='样例')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
    ]
