# Generated by Django 2.0.1 on 2018-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempted',
            field=models.PositiveIntegerField(default=0, verbose_name='尝试数'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=254, null=True, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='user',
            name='solved',
            field=models.PositiveIntegerField(default=0, verbose_name='解决数'),
        ),
    ]
